<a href="https://colab.research.google.com/github/Dydak811/analysis-everpeak/blob/main/everpeak_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello from Colab!")

In [1]:
import pandas as pd

# Create a sample DataFrame
data = {
    'Product': ['A', 'B', 'A', 'C', 'B', 'A'],
    'Region': ['East', 'West', 'East', 'North', 'West', 'South'],
    'Sales': [100, 150, 120, 90, 180, 110]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
display(df)

# Filter data for 'Product A'
product_a_sales = df[df['Product'] == 'A']

print("\nSales for Product A:")
display(product_a_sales)

# Calculate total sales per region
regional_sales = df.groupby('Region')['Sales'].sum().reset_index()

print("\nTotal Sales per Region:")
display(regional_sales)

Original DataFrame:

  Product Region  Sales
0       A   East    100
1       B   West    150
2       A   East    120
3       C  North     90
4       B   West    180
5       A  South    110

Sales for Product A:

  Product Region  Sales
0       A   East    100
2       A   East    120
5       A  South    110

Total Sales per Region:

  Region  Sales
0   East    220
1  North     90
2  South    110
3   West    330